[project]
name = "nasa-gcmd"
version = "0.1.0"
description = ""
authors = [
    {name = "Sam Woodcock", email = "samuel.woodcock@wsl.ch"},
]
dependencies = [
    "envidat-utils[dotenv]==1.0.3",
]
requires-python = ">=3.9"
license = {text = "MIT"}

[tool.pdm]
[tool.pdm.dev-dependencies]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
